// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.1
// 	protoc        v5.26.1
// source: teams_voicein/stt.proto

package teams_voicein

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HwRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *HwRequest) Reset() {
	*x = HwRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_teams_voicein_stt_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HwRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HwRequest) ProtoMessage() {}

func (x *HwRequest) ProtoReflect() protoreflect.Message {
	mi := &file_teams_voicein_stt_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HwRequest.ProtoReflect.Descriptor instead.
func (*HwRequest) Descriptor() ([]byte, []int) {
	return file_teams_voicein_stt_proto_rawDescGZIP(), []int{0}
}

type HwResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *HwResponse) Reset() {
	*x = HwResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_teams_voicein_stt_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HwResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HwResponse) ProtoMessage() {}

func (x *HwResponse) ProtoReflect() protoreflect.Message {
	mi := &file_teams_voicein_stt_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HwResponse.ProtoReflect.Descriptor instead.
func (*HwResponse) Descriptor() ([]byte, []int) {
	return file_teams_voicein_stt_proto_rawDescGZIP(), []int{1}
}

func (x *HwResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_teams_voicein_stt_proto protoreflect.FileDescriptor

var file_teams_voicein_stt_proto_rawDesc = []byte{
	0x0a, 0x17, 0x74, 0x65, 0x61, 0x6d, 0x73, 0x5f, 0x76, 0x6f, 0x69, 0x63, 0x65, 0x69, 0x6e, 0x2f,
	0x73, 0x74, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0d, 0x74, 0x65, 0x61, 0x6d, 0x73,
	0x5f, 0x76, 0x6f, 0x69, 0x63, 0x65, 0x69, 0x6e, 0x22, 0x0b, 0x0a, 0x09, 0x48, 0x77, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x26, 0x0a, 0x0a, 0x48, 0x77, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x32, 0x51, 0x0a,
	0x0c, 0x53, 0x70, 0x65, 0x65, 0x63, 0x68, 0x54, 0x6f, 0x54, 0x65, 0x78, 0x74, 0x12, 0x41, 0x0a,
	0x08, 0x53, 0x61, 0x79, 0x48, 0x65, 0x6c, 0x6c, 0x6f, 0x12, 0x18, 0x2e, 0x74, 0x65, 0x61, 0x6d,
	0x73, 0x5f, 0x76, 0x6f, 0x69, 0x63, 0x65, 0x69, 0x6e, 0x2e, 0x48, 0x77, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x19, 0x2e, 0x74, 0x65, 0x61, 0x6d, 0x73, 0x5f, 0x76, 0x6f, 0x69, 0x63,
	0x65, 0x69, 0x6e, 0x2e, 0x48, 0x77, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00,
	0x42, 0x3c, 0x5a, 0x3a, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6b,
	0x61, 0x6e, 0x61, 0x74, 0x61, 0x69, 0x64, 0x61, 0x72, 0x6f, 0x76, 0x2f, 0x74, 0x69, 0x6e, 0x6b,
	0x6f, 0x66, 0x66, 0x5f, 0x76, 0x6f, 0x69, 0x63, 0x65, 0x6b, 0x69, 0x74, 0x2f, 0x70, 0x6b, 0x67,
	0x2f, 0x74, 0x65, 0x61, 0x6d, 0x73, 0x5f, 0x76, 0x6f, 0x69, 0x63, 0x65, 0x69, 0x6e, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_teams_voicein_stt_proto_rawDescOnce sync.Once
	file_teams_voicein_stt_proto_rawDescData = file_teams_voicein_stt_proto_rawDesc
)

func file_teams_voicein_stt_proto_rawDescGZIP() []byte {
	file_teams_voicein_stt_proto_rawDescOnce.Do(func() {
		file_teams_voicein_stt_proto_rawDescData = protoimpl.X.CompressGZIP(file_teams_voicein_stt_proto_rawDescData)
	})
	return file_teams_voicein_stt_proto_rawDescData
}

var file_teams_voicein_stt_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_teams_voicein_stt_proto_goTypes = []interface{}{
	(*HwRequest)(nil),  // 0: teams_voicein.HwRequest
	(*HwResponse)(nil), // 1: teams_voicein.HwResponse
}
var file_teams_voicein_stt_proto_depIdxs = []int32{
	0, // 0: teams_voicein.SpeechToText.SayHello:input_type -> teams_voicein.HwRequest
	1, // 1: teams_voicein.SpeechToText.SayHello:output_type -> teams_voicein.HwResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_teams_voicein_stt_proto_init() }
func file_teams_voicein_stt_proto_init() {
	if File_teams_voicein_stt_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_teams_voicein_stt_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HwRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_teams_voicein_stt_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HwResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_teams_voicein_stt_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_teams_voicein_stt_proto_goTypes,
		DependencyIndexes: file_teams_voicein_stt_proto_depIdxs,
		MessageInfos:      file_teams_voicein_stt_proto_msgTypes,
	}.Build()
	File_teams_voicein_stt_proto = out.File
	file_teams_voicein_stt_proto_rawDesc = nil
	file_teams_voicein_stt_proto_goTypes = nil
	file_teams_voicein_stt_proto_depIdxs = nil
}
