// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v5.26.1
// source: teams_voicein/stt.proto

package teams_voicein

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	SpeechToText_Recognize_FullMethodName = "/teams_voicein.SpeechToText/Recognize"
)

// SpeechToTextClient is the client API for SpeechToText service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SpeechToTextClient interface {
	Recognize(ctx context.Context, in *SttRequest, opts ...grpc.CallOption) (*SttResponse, error)
}

type speechToTextClient struct {
	cc grpc.ClientConnInterface
}

func NewSpeechToTextClient(cc grpc.ClientConnInterface) SpeechToTextClient {
	return &speechToTextClient{cc}
}

func (c *speechToTextClient) Recognize(ctx context.Context, in *SttRequest, opts ...grpc.CallOption) (*SttResponse, error) {
	out := new(SttResponse)
	err := c.cc.Invoke(ctx, SpeechToText_Recognize_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SpeechToTextServer is the server API for SpeechToText service.
// All implementations must embed UnimplementedSpeechToTextServer
// for forward compatibility
type SpeechToTextServer interface {
	Recognize(context.Context, *SttRequest) (*SttResponse, error)
	mustEmbedUnimplementedSpeechToTextServer()
}

// UnimplementedSpeechToTextServer must be embedded to have forward compatible implementations.
type UnimplementedSpeechToTextServer struct {
}

func (UnimplementedSpeechToTextServer) Recognize(context.Context, *SttRequest) (*SttResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Recognize not implemented")
}
func (UnimplementedSpeechToTextServer) mustEmbedUnimplementedSpeechToTextServer() {}

// UnsafeSpeechToTextServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SpeechToTextServer will
// result in compilation errors.
type UnsafeSpeechToTextServer interface {
	mustEmbedUnimplementedSpeechToTextServer()
}

func RegisterSpeechToTextServer(s grpc.ServiceRegistrar, srv SpeechToTextServer) {
	s.RegisterService(&SpeechToText_ServiceDesc, srv)
}

func _SpeechToText_Recognize_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SttRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SpeechToTextServer).Recognize(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SpeechToText_Recognize_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SpeechToTextServer).Recognize(ctx, req.(*SttRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SpeechToText_ServiceDesc is the grpc.ServiceDesc for SpeechToText service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SpeechToText_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "teams_voicein.SpeechToText",
	HandlerType: (*SpeechToTextServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Recognize",
			Handler:    _SpeechToText_Recognize_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "teams_voicein/stt.proto",
}
